apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ssh://git@github.com/diwise/iot-agent-config?depth=1
  - ssh://git@github.com/diwise/iot-core-config?depth=1
  - ssh://git@github.com/diwise/iot-device-mgmt-config?depth=1
  - ssh://git@github.com/diwise/iot-device-mgmt-web-config?depth=1
  - ssh://git@github.com/diwise/iot-transform-fiware-config?depth=1
  - ssh://git@github.com/diwise/iot-events-config?depth=1
  - ssh://git@github.com/diwise/iot-things-config?depth=1
  - ssh://git@github.com/diwise/cip-functions-config?depth=1

transformers:
  - global-labels.yaml
