apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: context-broker
    app.kubernetes.io/part-of: cip-platform
  name: context-broker
  namespace: diwise
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: iot-agent
    app.kubernetes.io/part-of: iot-platform
  name: iot-agent
  namespace: diwise
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: iot-core
    app.kubernetes.io/part-of: iot-platform
  name: iot-core
  namespace: diwise
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: iot-device-mgmt
    app.kubernetes.io/part-of: iot-platform
  name: iot-device-mgmt
  namespace: diwise
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: iot-device-mgmt-web
    app.kubernetes.io/part-of: iot-platform
  name: iot-device-mgmt-web
  namespace: diwise
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: iot-transform-fiware
    app.kubernetes.io/part-of: iot-platform
  name: iot-transform-fiware
  namespace: diwise
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: orion-ld
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: cip-platform
  name: mongodb
  namespace: diwise
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: orion-ld
    app.kubernetes.io/name: orion-ld
    app.kubernetes.io/part-of: cip-platform
  name: orion-ld
  namespace: diwise
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: context-broker
    app.kubernetes.io/part-of: cip-platform
  name: context-broker
  namespace: diwise
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: context-broker
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: iot-agent
    app.kubernetes.io/part-of: iot-platform
  name: iot-agent
  namespace: diwise
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: iot-agent
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: iot-device-mgmt
    app.kubernetes.io/part-of: iot-platform
  name: iot-device-mgmt
  namespace: diwise
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: iot-device-mgmt
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: iot-device-mgmt-web
    app.kubernetes.io/part-of: iot-platform
  name: iot-device-mgmt-web
  namespace: diwise
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: iot-device-mgmt-web
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: orion-ld
    app.kubernetes.io/name: mongo-express
    app.kubernetes.io/part-of: cip-platform
  name: mongo-express
  namespace: diwise
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app.kubernetes.io/name: mongo-express
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: orion-ld
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: cip-platform
  name: mongodb
  namespace: diwise
spec:
  ports:
  - name: default-port
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app.kubernetes.io/name: mongodb
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: orion-ld
    app.kubernetes.io/name: orion-ld
    app.kubernetes.io/part-of: cip-platform
  name: orion-ld
  namespace: diwise
spec:
  ports:
  - name: default-port
    port: 80
    protocol: TCP
    targetPort: 1026
  selector:
    app.kubernetes.io/name: orion-ld
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: context-broker
    app.kubernetes.io/part-of: cip-platform
  name: context-broker
  namespace: diwise
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: context-broker
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: context-broker
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ghcr.io/diwise/context-broker@sha256:ec34bb56be331a0687c3200a2c6248347b6a91ae66b3da70547a4e7224fe79e9
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: default-port
        name: context-broker
        ports:
        - containerPort: 8080
          name: default-port
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 250Mi
          requests:
            cpu: 50m
            memory: 100Mi
        startupProbe:
          httpGet:
            path: /health
            port: default-port
        volumeMounts:
        - mountPath: /opt/diwise/config
          name: context-broker-cfg
          readOnly: true
      serviceAccountName: context-broker
      volumes:
      - configMap:
          name: context-broker-config-cm
        name: context-broker-cfg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: iot-agent
    app.kubernetes.io/part-of: iot-platform
  name: iot-agent
  namespace: diwise
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: iot-agent
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: iot-agent
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DEV_MGMT_URL
          value: http://iot-device-mgmt
        - name: MQTT_HOST
          valueFrom:
            secretKeyRef:
              key: mqtt-host
              name: authn-mqtt
        - name: MQTT_TOPIC_0
          valueFrom:
            secretKeyRef:
              key: mqtt-topic
              name: authn-mqtt
        - name: MQTT_USER
          valueFrom:
            secretKeyRef:
              key: mqtt-user
              name: authn-mqtt
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mqtt-password
              name: authn-mqtt
        - name: MSG_FWD_ENDPOINT
          value: http://iot-agent/api/v0/messages
        - name: RABBITMQ_HOST
          value: rabbitmq
        image: ghcr.io/diwise/iot-agent@sha256:f23833de271243e0f66f074b971ae5cc963ff0e8af4723a28a85bc7c9a8b08c7
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: default-port
        name: iot-agent
        ports:
        - containerPort: 8080
          name: default-port
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 250Mi
          requests:
            cpu: 50m
            memory: 100Mi
        startupProbe:
          httpGet:
            path: /health
            port: default-port
      serviceAccountName: iot-agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: iot-core
    app.kubernetes.io/part-of: iot-platform
  name: iot-core
  namespace: diwise
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: iot-core
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: iot-core
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DEV_MGMT_URL
          value: http://iot-device-mgmt
        - name: RABBITMQ_HOST
          value: rabbitmq
        image: ghcr.io/diwise/iot-core@sha256:a2f5781efd1e223cb943453b1afd6661e83a167696aa6e662e3f3818f9ab78c3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: default-port
        name: iot-core
        ports:
        - containerPort: 8080
          name: default-port
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 250Mi
          requests:
            cpu: 50m
            memory: 100Mi
        startupProbe:
          httpGet:
            path: /health
            port: default-port
      serviceAccountName: iot-core
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: iot-device-mgmt
    app.kubernetes.io/part-of: iot-platform
  name: iot-device-mgmt
  namespace: diwise
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: iot-device-mgmt
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: iot-device-mgmt
    spec:
      containers:
      - env:
        - name: RABBITMQ_HOST
          value: rabbitmq
        image: ghcr.io/diwise/iot-device-mgmt@sha256:224d2c8cd011a267460e97c1fd82651eed7a88121d19b5deec4af0801f9f3a92
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: default-port
        name: iot-device-mgmt
        ports:
        - containerPort: 8080
          name: default-port
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 250Mi
          requests:
            cpu: 50m
            memory: 100Mi
        startupProbe:
          httpGet:
            path: /health
            port: default-port
        volumeMounts:
        - mountPath: /opt/diwise/config
          name: conf-volume
          readOnly: true
        - mountPath: /opt/diwise/config/data
          name: conf-volume-data
          readOnly: true
      serviceAccountName: iot-device-mgmt
      volumes:
      - configMap:
          name: known-devices-cm
        name: conf-volume-data
      - configMap:
          name: dev-mgmt-cfg-cm
        name: conf-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: iot-device-mgmt-web
    app.kubernetes.io/part-of: iot-platform
  name: iot-device-mgmt-web
  namespace: diwise
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: iot-device-mgmt-web
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: iot-device-mgmt-web
    spec:
      containers:
      - image: ghcr.io/diwise/iot-device-mgmt-web@sha256:b7ef15beb09f8559b7af25fa7de529ff153a6ff05b279a5d96284d24534b6250
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: default-port
        name: iot-device-mgmt-web
        ports:
        - containerPort: 8080
          name: default-port
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 250Mi
          requests:
            cpu: 50m
            memory: 100Mi
        startupProbe:
          httpGet:
            path: /health
            port: default-port
        volumeMounts:
        - mountPath: /opt/app-root/src/device-management/config
          name: config-volume
      serviceAccountName: iot-device-mgmt-web
      volumes:
      - configMap:
          name: devmgmt-web-config
        name: config-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: iot-transform-fiware
    app.kubernetes.io/part-of: iot-platform
  name: iot-transform-fiware
  namespace: diwise
spec:
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: iot-transform-fiware
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: iot-transform-fiware
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NGSI_CB_URL
          value: http://context-broker
        - name: RABBITMQ_HOST
          value: rabbitmq
        image: ghcr.io/diwise/iot-transform-fiware@sha256:e67ebbb7d747add74eda44cae3fc985c895cb17c69ea562a2d53852acb33c8c9
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: default-port
        name: iot-transform-fiware
        ports:
        - containerPort: 8080
          name: default-port
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 250Mi
          requests:
            cpu: 50m
            memory: 100Mi
        startupProbe:
          httpGet:
            path: /health
            port: default-port
      serviceAccountName: iot-transform-fiware
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: orion-ld
    app.kubernetes.io/name: mongo-express
    app.kubernetes.io/part-of: cip-platform
  name: mongo-express
  namespace: diwise
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo-express
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo-express
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongodb
        - name: ME_CONFIG_MONGODB_PORT
          value: "27017"
        - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
          value: "true"
        - name: ME_CONFIG_MONGODB_AUTH_DATABASE
          value: admin
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: authn-mongodb
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: authn-mongodb
        image: mongo-express
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: default-port
        name: mongo-express
        ports:
        - containerPort: 8081
          name: default-port
          protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 250Mi
        startupProbe:
          httpGet:
            path: /
            port: default-port
      serviceAccountName: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: orion-ld
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: cip-platform
  name: mongodb
  namespace: diwise
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: authn-mongodb
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: authn-mongodb
        image: mongo:5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: default-port
        name: mongodb
        ports:
        - containerPort: 27017
          name: default-port
          protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 250Mi
        startupProbe:
          httpGet:
            path: /health
            port: default-port
        volumeMounts:
        - mountPath: /data/db
          name: db-volume
      serviceAccountName: mongodb
      volumes:
      - emptyDir: {}
        name: db-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: orion-ld
    app.kubernetes.io/name: orion-ld
    app.kubernetes.io/part-of: cip-platform
  name: orion-ld
  namespace: diwise
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: orion-ld
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orion-ld
    spec:
      containers:
      - command:
        - orionld
        - -fg
        - -multiservice
        - -ngsiv1Autocast
        - -experimental
        - -logLevel
        - DEBUG
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ORIONLD_MONGO_HOST
          value: mongodb
        - name: ORIONLD_MONGO_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: authn-mongodb
        - name: ORIONLD_MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: authn-mongodb
        - name: ORIONLD_DISABLE_FILE_LOG
          value: "TRUE"
        image: quay.io/fiware/orion-ld@sha256:a65adbface4d5467add735d01c7204951e3c474ef8fc901fbd3a2af285beafea
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /ngsi-ld/v1/types
            port: default-port
          timeoutSeconds: 2
        name: orion-ld
        ports:
        - containerPort: 1026
          name: default-port
          protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 250Mi
        startupProbe:
          failureThreshold: 6
          httpGet:
            path: /ngsi-ld/v1/types
            port: default-port
          periodSeconds: 10
          timeoutSeconds: 2
      serviceAccountName: orion-ld
