version: '3'
services:
  
  pgadmin:
    image: dpage/pgadmin4:8.3
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@diwise.io
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./configs/pgadmin/servers.json:/pgadmin4/servers.json
      
  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: 'mongodb'
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_AUTH_DATABASE: 'admin'
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'admin'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'password'
      ME_CONFIG_BASICAUTH_USERNAME: ''
    depends_on:
      orion-ld:
        condition: service_healthy
    ports:
      - '5051:8081'

volumes:
  pgadmin-data: ~
