version: '3'
services:

  iot-agent:
    depends_on:
      otel-collector:
        condition: service_started
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
    logging:
      driver: fluentd
      options:
#        fluentd-address: fluentbit:24224
        fluentd-async: 'true'
    links:
      - fluentbit


  iot-core:
    depends_on:
      otel-collector:
        condition: service_started
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
    logging:
      driver: fluentd
      options:
#        fluentd-address: fluentbit:24224
        fluentd-async: 'true'
    links:
      - fluentbit


  iot-device-mgmt:
    depends_on:
      otel-collector:
        condition: service_started
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
    logging:
      driver: fluentd
      options:
#        fluentd-address: fluentbit:24224
        fluentd-async: 'true'
    links:
      - fluentbit


  iot-events:
    depends_on:
      otel-collector:
        condition: service_started
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
    logging:
      driver: fluentd
      options:
#        fluentd-address: fluentbit:24224
        fluentd-async: 'true'
    links:
      - fluentbit


  iot-transform-fiware:
    depends_on:
      otel-collector:
        condition: service_started
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
    logging:
      driver: fluentd
      options:
#        fluentd-address: fluentbit:24224
        fluentd-async: 'true'
    links:
      - fluentbit


  iot-things:
    depends_on:
      otel-collector:
        condition: service_started
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
    logging:
      driver: fluentd
      options:
#        fluentd-address: fluentbit:24224
        fluentd-async: 'true'
    links:
      - fluentbit


  cip-functions:
    depends_on:
      otel-collector:
        condition: service_started
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
    logging:
      driver: fluentd
      options:
#        fluentd-address: fluentbit:24224
        fluentd-async: 'true'
    links:
      - fluentbit


  context-broker:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
    depends_on:
      otel-collector:
        condition: service_started
    logging:
      driver: fluentd
      options:
#        fluentd-address: fluentbit:24224
        fluentd-async: 'true'
    links:
      - fluentbit


  otel-collector:
    image: 'otel/opentelemetry-collector:0.86.0'
    command: '--config /etc/otel-config.yaml'
    depends_on:
      loki:
        condition: service_healthy
      mimir:
        condition: service_healthy
      tempo:
        condition: service_healthy
    volumes:
     - ./configs/opentelemetry/otel-config.yaml:/etc/otel-config.yaml
    restart: always
    ports:
      - '4318'


  grafana:
    volumes:
      - ./configs/grafana/dashboard-provisioning.yaml:/etc/grafana/provisioning/dashboards/provisioning.yaml
      - ./configs/grafana/dashboards:/etc/dashboards
      - ./configs/grafana/datasources:/etc/grafana/provisioning/datasources


  tempo:
    image: grafana/tempo:2.2.3
    command: [ '-config.file=/etc/tempo.yaml' ]
    volumes:
      - ./configs/tempo/tempo-local.yaml:/etc/tempo.yaml
      - /tmp/tempo-data/:/tmp/tempo
    ports:
      - '14268'  # jaeger ingest
      - '3200'   # tempo
      - '4317'  # otlp grpc
      - '4318'  # otlp http
      - '9411'   # zipkin
    healthcheck:
      test: wget -q --tries=1 -O- http://127.0.0.1:3200/ready|grep -q "ready"
      interval: 2s
      timeout: 5s
      retries: 24
      start_period: 10s


  loki:
    image: grafana/loki:2.8.5
    ports:
      - '3100'
    command: [ '-config.file=/etc/loki/local-config.yaml' ]
    healthcheck:
      test: wget -q --tries=1 -O- http://127.0.0.1:3100/ready|grep -q "ready"
      interval: 10s
      timeout: 5s
      retries: 3
  

  mimir:
    image: grafana/mimir:2.10.0
    command: [ '--config.file=/etc/mimir/compose.yaml' ]
    volumes:
      - ./configs/mimir/config.yaml:/etc/mimir/compose.yaml
    ports:
      - '9009'
    healthcheck:
      test: wget -q --tries=1 -O- http://127.0.0.1:9009/ready|grep -q "ready"
      interval: 2s
      timeout: 5s
      retries: 24
      start_period: 10s


  # We will be setting up fluent-bit as a docker logging driver to collect log output from the other containers and forward it to loki
  # See https://kevcodez.de/posts/2019-08-10-fluent-bit-docker-logging-driver-elasticsearch/
  fluentbit:
    image: bitnami/fluent-bit:1.9.8
    restart: always
    depends_on:
      loki:
        condition: service_healthy
    volumes:
      - ./configs/diwise/fluent-bit/fluent-bit.conf:/opt/bitnami/fluent-bit/conf/fluent-bit.conf
      - ./configs/diwise/fluent-bit/log-filter.lua:/opt/bitnami/fluent-bit/conf/log-filter.lua
      - ./configs/diwise/fluent-bit/json.lua:/usr/local/share/lua/5.1/json.lua
    ports:
      - '2020:2020'
      - '24224:24224'
      - '24224:24224/udp'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:2020/api/v1/health"]
      interval: 2s
      timeout: 5s
      retries: 24
      start_period: 10s
