services:

  diwise-web:
    depends_on:
      otel-collector:
        condition: service_started
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'

  iot-agent:
    depends_on:
      otel-collector:
        condition: service_started
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'


  iot-core:
    depends_on:
      otel-collector:
        condition: service_started
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'


  iot-device-mgmt:
    depends_on:
      otel-collector:
        condition: service_started
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'


  iot-events:
    depends_on:
      otel-collector:
        condition: service_started
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'


  iot-transform-fiware:
    depends_on:
      otel-collector:
        condition: service_started
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'


  iot-things:
    depends_on:
      otel-collector:
        condition: service_started
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'


  context-broker:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
    depends_on:
      otel-collector:
        condition: service_started


  otel-collector:
    image: 'otel/opentelemetry-collector:0.121.0'
    command: '--config /etc/otel-config.yaml'
    depends_on:
      loki:
        condition: service_healthy
      mimir:
        condition: service_started
      tempo:
        condition: service_healthy
    volumes:
     - ./configs/opentelemetry/otel-config.yaml:/etc/otel-config.yaml
    restart: always
    ports:
      - '4318'


  grafana:
    volumes:
      - ./configs/grafana/dashboard-provisioning.yaml:/etc/grafana/provisioning/dashboards/provisioning.yaml
      - ./configs/grafana/dashboards:/etc/dashboards
      - ./configs/grafana/datasources:/etc/grafana/provisioning/datasources


  tempo:
    image: docker.io/grafana/tempo:2.7.1
    command: [ '-config.file=/etc/tempo.yaml' ]
    volumes:
      - ./configs/tempo/tempo-local.yaml:/etc/tempo.yaml
      - /tmp/tempo-data/:/tmp/tempo
    ports:
      - '14268'  # jaeger ingest
      - '3200'   # tempo
      - '4317'  # otlp grpc
      - '4318'  # otlp http
      - '9411'   # zipkin
    healthcheck:
      test: wget -q --tries=1 -O- http://127.0.0.1:3200/ready|grep -q "ready"
      interval: 2s
      timeout: 5s
      retries: 24
      start_period: 10s


  loki:
    image: docker.io/grafana/loki:3.4.2
    ports:
      - '3100'
    command: [ '-config.file=/etc/loki/local-config.yaml' ]
    healthcheck:
      test: wget -q --tries=1 -O- http://127.0.0.1:3100/ready|grep -q "ready"
      interval: 10s
      timeout: 5s
      retries: 3
  

  mimir:
    image: docker.io/grafana/mimir:2.15.0
    command: [ '--config.file=/etc/mimir/compose.yaml' ]
    volumes:
      - ./configs/mimir/config.yaml:/etc/mimir/compose.yaml
    ports:
      - '9009'
#    healthcheck:
#      test: wget -q --tries=1 -O- http://mimir:9009/ready|grep -q "ready"
#      interval: 2s
#      timeout: 5s
#      retries: 24
#      start_period: 10s
