version: '3'
services:
  iot-agent:
    image: 'ghcr.io/diwise/iot-agent:prod-21bfc43b8a6ba6b4efe41b40beaebe1ead742779'
    restart: always
    depends_on:
      - keycloak
      - rabbitmq
      - iot-core
      - iot-device-mgmt
    environment:
      MQTT_DISABLED: 'true'
      RABBITMQ_HOST: 'rabbitmq'
      DEV_MGMT_URL: 'http://iot-device-mgmt:8080'
      MSG_FWD_ENDPOINT: 'http://iot-agent:8080/api/v0/messages'
      OAUTH2_TOKEN_URL: 'http://keycloak:8080/realms/diwise-local/protocol/openid-connect/token'
      OAUTH2_CLIENT_ID: 'diwise-devmgmt-api'
      OAUTH2_CLIENT_SECRET: '615241704865544572616B61474E494B65504861574E7449744943655269654E'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
    ports:
      - '8090:8080'


  iot-core:
    image: 'ghcr.io/diwise/iot-core:prod-806968b116e8e53ee7093ce8af10d540432a0847'
    restart: always
    depends_on:
      - keycloak
      - rabbitmq
    environment:
      RABBITMQ_HOST: 'rabbitmq'
      DEV_MGMT_URL: 'http://iot-device-mgmt:8080'
      OAUTH2_TOKEN_URL: 'http://keycloak:8080/realms/diwise-local/protocol/openid-connect/token'
      OAUTH2_CLIENT_ID: 'diwise-devmgmt-api'
      OAUTH2_CLIENT_SECRET: '615241704865544572616B61474E494B65504861574E7449744943655269654E'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'


  iot-device-mgmt:
    image: 'ghcr.io/diwise/iot-device-mgmt:prod-2d8799e86f48c9e516a49cf64a5c8625ab340396'
    restart: always
    depends_on:
      - keycloak
      - rabbitmq
    environment:
      RABBITMQ_HOST: 'rabbitmq'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
    volumes:
      - ./configs/diwise/devices.csv:/opt/diwise/config/devices.csv
      - ./configs/diwise/devmgmt-auth.rego:/opt/diwise/config/authz.rego
    ports:
      - '8080'


  iot-device-mgmt-web:
    image: 'ghcr.io/diwise/iot-device-mgmt-web:prod-036031601b4d02806b55cbeb8e67f44ad4f2870b'
    restart: always
    depends_on:
      - iot-device-mgmt
    environment:
      DEVICE_MGMT_URL: http://iot-device-mgmt:8080
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
    ports:
      - '8080:8080'


  iot-transform-fiware:
    image: 'ghcr.io/diwise/iot-transform-fiware:prod-b64c44b982f360f6ef44134774e48fabb6bf24fa'
    restart: always
    depends_on:
      - rabbitmq
      - context-broker
    environment:
      NGSI_CB_URL: 'http://context-broker:8080'
      RABBITMQ_HOST: 'rabbitmq'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'


  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    #image: 'arm64v8/rabbitmq:3.8'
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'bitnami'
    ports:
      - '4369'
      - '5672'
      - '25672'
      - '15672'
    volumes:
      - 'rabbitmq_data:/bitnami'


  context-broker:
    image: 'ghcr.io/diwise/context-broker:prod-3be1c881e328bee17f3de234c07e06df4ed3afcd'
    restart: always
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
    depends_on:
      - orion-ld
    volumes:
      - ./configs/diwise/context-broker.yaml:/opt/diwise/config/default.yaml
    ports:
      - '8081:8080'


  orion-ld:
    image: 'quay.io/fiware/orion-ld@sha256:ea838e5b405170b6d42af9035a30454a21870f7f3738db73da27585bf6a478b3'
    restart: always
    environment:
      ORIONLD_MONGO_HOST: 'mongodb'
      ORIONLD_MONGO_USER: 'admin'
      ORIONLD_MONGO_PASSWORD: 'password'
      ORIONLD_LOG_FOR_HUMANS: 'TRUE'
      ORIONLD_TROE:	'FALSE'
      ORIONLD_DISABLE_FILE_LOG: 'TRUE'
    depends_on:
      - mongodb
    ports:
      - '8082:1026'


  mongodb:
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    ports:
      - '27017'
    command: --nojournal --quiet
    volumes:
      - mongo-db:/data


  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: 'mongodb'
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_AUTH_DATABASE: 'admin'
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'admin'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'password'
      ME_CONFIG_BASICAUTH_USERNAME: ''
    depends_on:
        - mongodb
    ports:
      - '8083:8081'


  otel-collector:
    image: 'otel/opentelemetry-collector:0.52.0'
    command: '--config /etc/otel-config.yaml'
    volumes:
     - ./configs/opentelemetry/otel-config.yaml:/etc/otel-config.yaml
    restart: always
    ports:
      - '4318'


  tempo:
    image: grafana/tempo:latest
    command: [ '-config.file=/etc/tempo.yaml' ]
    volumes:
      - ./configs/tempo/tempo-local.yaml:/etc/tempo.yaml
      - /tmp/tempo-data/:/tmp/tempo
    ports:
      - '14268'  # jaeger ingest
      - '3200'   # tempo
      - '4317'  # otlp grpc
      - '4318'  # otlp http
      - '9411'   # zipkin


  grafana:
    image: grafana/grafana:8.5.10
    environment:
      GF_SECURITY_ADMIN_USER: diwise
      GF_SECURITY_ADMIN_PASSWORD: diwise
    volumes:
      - ./configs/grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    ports:
      - '8088:3000'


  keycloak:
    image: quay.io/keycloak/keycloak:19.0
    command:
    - 'start-dev'
    - '-Dkeycloak.migration.action=import'
    - '-Dkeycloak.migration.provider=singleFile'
    - '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING'
    - '-Dkeycloak.migration.file=/application-realm.json'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8888:8080'
    volumes:
     - type: bind
       source: ./configs/keycloak/realm.json
       target: /application-realm.json
       read_only: true
volumes:
  rabbitmq_data:
    driver: local
  grafana-data:
  mongo-db: ~
