version: '3'
services:

  proxy:
    image: 'registry.access.redhat.com/ubi8/nginx-120'
    command:
      - nginx
      - -g
      - daemon off;
    restart: always
    depends_on:
      context-broker:
        condition: service_healthy
      iot-device-mgmt-web:
        condition: service_healthy
    volumes:
      - ./configs/proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/proxy/openssl/server.crt:/etc/ssl/server.crt
      - ./configs/proxy/openssl/server.key:/etc/ssl/server.key
      - ./configs/keycloak/openssl/server.pem:/etc/ssl/kc-server.crt
      - ./configs/proxy/openssl/server.key:/etc/ssl/kc-server.key
    ports:
      - '8443:443'
      - '8444:444'


  iot-device-mgmt-web:
    image: 'diwise/iot-device-mgmt-web:latest'
    restart: always
    depends_on:
      iot-device-mgmt:
        condition: service_healthy
    environment:
      DEVICE_MGMT_URL: http://iot-device-mgmt:8080
    volumes:
      - ./configs/diwise/devmgmtweb-kc.json:/opt/app-root/src/device-management/config/keycloak.json
    ports:
      - '8080'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s


  iot-agent:
    image: 'ghcr.io/diwise/iot-agent:prod-09c417702f22ae2f5efc21874844f9e788061920'
    restart: always
    depends_on:
      iot-device-mgmt:
        condition: service_healthy
    environment:
      MQTT_DISABLED: 'true'
      RABBITMQ_HOST: 'rabbitmq'
      DEV_MGMT_URL: 'http://iot-device-mgmt:8080'
      MSG_FWD_ENDPOINT: 'http://iot-agent:8080/api/v0/messages'
      OAUTH2_TOKEN_URL: 'http://keycloak:8080/realms/diwise-local/protocol/openid-connect/token'
      OAUTH2_CLIENT_ID: 'diwise-devmgmt-api'
      OAUTH2_CLIENT_SECRET: '615241704865544572616B61474E494B65504861574E7449744943655269654E'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
    ports:
      - '8080'


  iot-core:
    image: 'ghcr.io/diwise/iot-core:prod-4534c4020732c7d5fddae993edccdca7596e9982'
    restart: always
    depends_on:
      iot-device-mgmt:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: 'rabbitmq'
      DEV_MGMT_URL: 'http://iot-device-mgmt:8080'
      OAUTH2_TOKEN_URL: 'http://keycloak:8080/realms/diwise-local/protocol/openid-connect/token'
      OAUTH2_CLIENT_ID: 'diwise-devmgmt-api'
      OAUTH2_CLIENT_SECRET: '615241704865544572616B61474E494B65504861574E7449744943655269654E'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
    ports:
      - '8080'


  iot-device-mgmt:
    image: 'ghcr.io/diwise/iot-device-mgmt:prod-de28a28cb534feef4deebcbddda7f2a1e542c2a1'
    restart: always
    depends_on:
      keycloak:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: 'rabbitmq'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
    volumes:
      - ./configs/diwise/devices.csv:/opt/diwise/config/devices.csv
      - ./configs/diwise/devmgmt-auth.rego:/opt/diwise/config/authz.rego
    ports:
      - '8080'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s


  iot-transform-fiware:
    image: 'ghcr.io/diwise/iot-transform-fiware:prod-6945322449cbc116aca22ab88a6f091c592f5f6b'
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      context-broker:
        condition: service_healthy
    environment:
      NGSI_CB_URL: 'http://context-broker:8080'
      RABBITMQ_HOST: 'rabbitmq'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'


  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    #image: 'arm64v8/rabbitmq:3.8'
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'bitnami'
    ports:
      - '4369'
      - '5672'
      - '25672'
      - '15672'
    volumes:
      - 'rabbitmq_data:/bitnami'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  context-broker:
    image: 'ghcr.io/diwise/context-broker:prod-5d59a59feb37087eae37a7e555ba00955ecb577d'
    restart: always
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
    depends_on:
      keycloak:
        condition: service_healthy
      orion-ld:
        condition: service_healthy
    volumes:
      - ./configs/diwise/context-broker.yaml:/opt/diwise/config/default.yaml
    ports:
      - '8080'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 2s


  orion-ld:
    image: 'quay.io/fiware/orion-ld@sha256:ea838e5b405170b6d42af9035a30454a21870f7f3738db73da27585bf6a478b3'
    restart: always
    environment:
      ORIONLD_MONGO_HOST: 'mongodb'
      ORIONLD_MONGO_USER: 'admin'
      ORIONLD_MONGO_PASSWORD: 'password'
      ORIONLD_LOG_FOR_HUMANS: 'TRUE'
      ORIONLD_TROE:	'FALSE'
      ORIONLD_DISABLE_FILE_LOG: 'TRUE'
    depends_on:
        mongodb:
          condition: service_started
    ports:
      - '1026'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1026/ngsi-ld/v1/types"]
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 2s


  mongodb:
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    ports:
      - '27017'
    command: --nojournal --quiet
    volumes:
      - mongo-db:/data


  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: 'mongodb'
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_AUTH_DATABASE: 'admin'
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'admin'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'password'
      ME_CONFIG_BASICAUTH_USERNAME: ''
    depends_on:
        orion-ld:
          condition: service_healthy
    ports:
      - '8183:8081'


  otel-collector:
    image: 'otel/opentelemetry-collector:0.52.0'
    command: '--config /etc/otel-config.yaml'
    volumes:
     - ./configs/opentelemetry/otel-config.yaml:/etc/otel-config.yaml
    restart: always
    ports:
      - '4318'


  tempo:
    image: grafana/tempo:latest
    command: [ '-config.file=/etc/tempo.yaml' ]
    volumes:
      - ./configs/tempo/tempo-local.yaml:/etc/tempo.yaml
      - /tmp/tempo-data/:/tmp/tempo
    ports:
      - '14268'  # jaeger ingest
      - '3200'   # tempo
      - '4317'  # otlp grpc
      - '4318'  # otlp http
      - '9411'   # zipkin


  grafana:
    image: grafana/grafana:8.5.10
    environment:
      GF_SERVER_DOMAIN: diwise.local
      GF_SERVER_ROOT_URL: https://diwise.local:8443/grafana/
      GF_SERVER_SERVER_FROM_SUBPATH: "true"
      GF_SECURITY_ADMIN_USER: diwise
      GF_SECURITY_ADMIN_PASSWORD: diwise
    volumes:
      - ./configs/grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    ports:
      - '3000'


  keycloak:
    image: quay.io/keycloak/keycloak:19.0
    command:
    - 'start-dev'
    - '--hostname=iam.diwise.local'
    - '--hostname-port=8444'
    - '--proxy=edge'
    - '--health-enabled=true'
    - '-Dkeycloak.migration.action=import'
    - '-Dkeycloak.migration.provider=singleFile'
    - '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING'
    - '-Dkeycloak.migration.file=/application-realm.json'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8080'
    volumes:
     - ./configs/keycloak/realm.json:/application-realm.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  rabbitmq_data:
    driver: local
  grafana-data:
  mongo-db: ~
