version: '3'
services:
  orion-ld:
    depends_on:
      timescale:
        condition: service_healthy
    environment:
      ORIONLD_TROE: 'TRUE'
      ORIONLD_TROE_USER: 'orion'
      ORIONLD_TROE_PWD: 'orion'
      ORIONLD_TROE_HOST: 'timescale'

  timescale:
    image: timescale/timescaledb-ha:pg14-latest    
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U orion" ]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 60s
    environment:
      POSTGRES_USER: 'orion'
      POSTGRES_PASSWORD: 'orion'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - "5432"
    networks:
      - default

  mintaka:
    image: fiware/mintaka:0.5.25
    restart: always
    environment:
      DATASOURCES_DEFAULT_HOST: 'timescale'
      DATASOURCES_DEFAULT_USERNAME: 'orion'
      DATASOURCES_DEFAULT_PASSWORD: 'orion'
      DATASOURCES_DEFAULT_DATABSE: 'orion'
    ports:
      - "8080"
    networks:
      - default
      