apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ssh://git@github.com/diwise/context-broker-config?depth=1
- ./resources/mongodb.yaml
- ./resources/orion-ld.yaml

transformers:
  - global-labels.yaml
