apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
      nodeGraph:
        enabled: true
 #     serviceMap:
 #       datasourceUid: 'prometheus'
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
      - datasourceName: Tempo
        datasourceUid: tempo
        matcherRegex: '"traceID":\s?"(\w+)'
        name: TraceID
        url: $${__value.raw}
  - name: Mimir
    type: prometheus
    url: http://mimir:9009/prometheus
