receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 5s
        static_configs:
        - targets: ['0.0.0.0:8888']
      - job_name: 'rabbitmq'
        scrape_interval: 5s
        static_configs:
        - targets: ['rabbitmq:15692']

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

  otlp:
    endpoint: 'tempo:4317'
    tls:
      insecure: true

  otlphttp/logs:
    endpoint: http://loki:3100/otlp

  otlphttp/metrics:
    endpoint: http://mimir:9009/otlp

  prometheusremotewrite:
    endpoint: "http://mimir:9009/api/v1/push"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/logs]

    metrics/otlp:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/metrics]

    metrics/prom:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]

  telemetry:
    logs:
      level: WARN
