receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  logging:
    loglevel: info
  otlp:
    endpoint: 'tempo:4317'
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp,logging]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
  telemetry:
    logs:
      level: error
