receivers:
  otlp:
    protocols:
      grpc:
      http:
  
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 5s
        static_configs:
        - targets: ['0.0.0.0:8888']
      - job_name: 'rabbitmq'
        scrape_interval: 5s
        static_configs:
        - targets: ['rabbitmq:15692']

processors:
  batch:

exporters:
  logging:
    loglevel: info
  otlp:
    endpoint: 'tempo:4317'
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: "http://mimir:9009/api/v1/push"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp,logging]

    metrics:
      receivers: [otlp,prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite,logging]
  telemetry:
    logs:
      level: error
